set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

set -g default-terminal "screen-256color"
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g history-limit 10000
set -g escape-time 0

set -g status-style "bg=#101010,fg=#FFFFFF"
set -g status-position top

set -g default-terminal "screen-256color"
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g default-terminal "screen-256color"
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g history-limit 10000
set -g escape-time 0

set -g status-style "bg=#101010,fg=#FFFFFF"
set -g status-position top
set -g status-interval 1
set -g status-left-length 40
set -g status-right-length 60

setw -g window-status-style "bg=#161616,fg=#FEFEFE"
setw -g window-status-current-style "bg=#232323,fg=#A0A0A0"
setw -g window-status-format " #I:#W#F "
setw -g window-status-current-format " #I:#W#F "

set -g pane-border-style "fg=#505050"
set -g pane-active-border-style "fg=#65737E"

set -g message-style "bg=#343434,fg=#99FFE4"
set -g message-command-style "bg=#343434,fg=#FFC799"

set -g display-panes-colour "#65737E"
set -g display-panes-active-colour "#FFCFA8"

set -g status-left "\
#[fg=#FFCFA8,bg=#101010] ❖ \
#[fg=#FFFFFF]#S \
#[fg=#65737E]│ \
#[fg=#99FFE4]#I:#P \
#[fg=#65737E]│ \
#[fg=#FFCFA8]#{?client_prefix,󰌌,}"

set -g status-right "\
#[fg=#65737E]#{?window_zoomed_flag, 󰊕 ,}\
#[fg=#65737E]#{?pane_synchronized, 󰓦 ,}\
#[fg=#65737E] %Y-%m-%d \
#[fg=#99FFE4] %H:%M "

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'
